#!/bin/bash
#SBATCH -J sequential_test
#SBATCH -o st_%j.out
#SBATCH -e st_%j.err
#SBATCH --mail-user francesco.biscacciacarrara@studenti.unipd.it 
#SBATCH --mail-type ALL
#SBATCH -n 1
#SBATCH -p allgroups
#SBATCH -t 04:30:00
#SBATCH --mem 20G

cd $SLURM_SUBMIT_DIR

./test_seq