#!/bin/bash
#SBATCH -J BitonicMerge_32
#SBATCH -o pt_32_%j.out
#SBATCH -e pt_32_%j.err
#SBATCH --mail-user francesco.biscacciacarrara@studenti.unipd.it 
#SBATCH --mail-type ALL
#SBATCH -n 32
#SBATCH -p allgroups
#SBATCH -t 01:30:00
#SBATCH --mem 20G

cd $SLURM_SUBMIT_DIR

mpirun -np $SLURM_NTASKS ./test_par